# Generated by Django 5.0.6 on 2024-07-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='animes',
            field=models.ManyToManyField(blank=True, related_name='users', to='anime.anime'),
        ),
    ]
