# Generated by Django 5.0.6 on 2024-07-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_cover_image_alter_user_animes'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episod_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='episode_cover_img/'),
        ),
    ]
