# Generated by Django 5.0.6 on 2024-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_episode_episod_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_cover_img/'),
        ),
    ]
