# Generated by Django 5.0.6 on 2024-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='blank-profile-picture-973460_1280.png', null=True, upload_to='profile_img/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
