# Generated by Django 5.0.6 on 2024-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_options_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='icons/blank-profile-picture-973460_1280.png', null=True, upload_to='profile_img/'),
        ),
    ]
