# Generated by Django 5.0.6 on 2024-07-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='download.jpg', null=True, upload_to='profile_img/'),
        ),
    ]
